POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "username": "admin@example.com",
  "password": "secret"
}

###

POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "test2@test2.com",
  "name": "Test2 User"
}