POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "test@test.com",
  "name": "Test User"
}
###
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiJzZWNyZXQiLCJpYXQiOjE3NTUwMDMxMzgsImV4cCI6MTc1NTM1OTUzOH0.P_KNWv1CMFDVAjiU24QlCQzAJkXLZRBuEw5cHtG0bos

###

PUT http://localhost:3001/api/users/test@test.com
Content-Type: application/json

{
  "newUsername": "test",
  "name": "Test User5"
}

###

GET http://localhost:3001/api/users/1?read=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiJzZWNyZXQiLCJpYXQiOjE3NTUwMDMxMzgsImV4cCI6MTc1NTM1OTUzOH0.P_KNWv1CMFDVAjiU24QlCQzAJkXLZRBuEw5cHtG0bos