POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "test@test.com",
  "name": "Test User"
}
###
GET http://localhost:3001/api/users

###

PUT http://localhost:3001/api/users/test@test.com
Content-Type: application/json

{
  "newUsername": "test",
  "name": "Test User5"
}

###

GET http://localhost:3001/api/users/1